---

- name: Provision example HelloWorld container
  hosts: all
  tasks:

    - name: Say Hello
      debug: msg="Hello Ansible"

    - name: Update apt cache
      apt:
        update_cache: yes
      become: yes

    - name: Remove possible docker leftovers
      apt:
        name: "{{ item }}"
        state: absent
      become: yes
      # performs this task with multiple package names
      with_items:
        - docker
        - docker-engine
        - docker.io
        - containerd
        - runc

    - name: Install docker dependencies
      apt:
        name: "{{ item }}"
        state: present
      become: yes
      with_items:
        - ca-certificates
        - curl
        - gnupg
        - lsb-release

    - name: Add GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
      become: yes

    - name: Add Docker repository to apt
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present
      become: yes

    - name: Install docker
      apt:
        name: "{{ item }}"
        state: present
      become: yes
      with_items:
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-compose-plugin

    - name: Install Docker module's dependencies
      apt:
        name: python3-pip
        state: present
      become: yes

    - name: Install Docker module's pip dependencies
      pip:
        name: "{{ item }}"
      with_items:
        - setuptools
        - virtualenv
        - docker
      become: yes

    - name: Reboot if needed
      reboot:
        reboot_command: shutdown -r now removes=/var/run/reboot-required
      become: yes

    - name: Run hello-world container
      community.docker.docker_container:
        name: hello
        image: crccheck/hello-world
        auto_remove: yes
        ports:
          - "80:8000"
      become: yes
