---

- name: Setup SWOZO user
  import_playbook: ../../administration/setup-user.yml
  vars:
    new_user: swozo

- name: Install docker
  import_playbook: ../docker/install-docker.yml

- name: Create directory for Jupyter config
  import_playbook: ../../administration/create-directory.yml
  vars:
    path: /home/swozo/.jupyter
    user: swozo

- name: Create directory for user's files
  import_playbook: ../../administration/create-directory.yml
  vars:
    path: /home/swozo/jupyter
    user: swozo

- name: Copy Jupyter config file
  hosts: all
  tasks:
    - name: Copy template and set password
      template:
        src: ./jupyter_notebook_config.j2
        dest: /home/swozo/.jupyter/jupyter_notebook_config.py
        owner: swozo

- name: Run jupyter
  import_playbook: run-jupyter.yml
