---

- name: Run jupyter container
  hosts: all
  tasks:
    - name: Run jupyter container
      community.docker.docker_container:
        name: jupyter
        image: jupyter/datascience-notebook
        auto_remove: yes
        ports:
          - "80:8888"
        mounts:
          - source: /home/swozo/jupyter
            target: /home/jovyan/work
            type: bind
          - source: /home/swozo/.jupyter/jupyter_notebook_config.py
            target: /home/jovyan/.jupyter/jupyter_notebook_config.py
            type: bind
      become: yes
