---

- name: Create a directory if it does not exist
  hosts: all
  import_playbook: ./create-directory.yaml
  vars:
    path: '{{ path_to }}'

- name: Copy file to remote host
  hosts: all
  become: yes
  become_user: '{{ user }}'
  tasks:
    - name: Copy content of directory to remote host
      copy:
        src: '{{ path_from }}'
        dest: '{{ path_to }}'
        owner: '{{ user }}'
        group: '{{ user }}'
        mode: '0777'
