---

- name: Copy user's workdir to bucket
  hosts: all
  become: yes
  tasks:
    - name: Create an archive
      community.general.archive:
        path: '{{ source_directory }}'
        dest: '/tmp/{{ target_filename }}'
        format: zip
        force_archive: yes
