---

- name: Setup SWOZO user
  hosts: all
  tasks:
    - name: Setup user
      user:
        create_home: yes
        home: /home/swozo
        name: swozo
        groups:
          - "sudo"

      become: yes
