---

- name: Setup user
  hosts: all
  tasks:
    - name: Setup user
      user:
        create_home: yes
        home: '/home/{{ user }}'
        name: '{{ user }}'
        groups:
          - "sudo"

      become: yes
