---

- name: Setup SWOZO user
  import_playbook: ../../administration/setup-user.yml
  vars:
    new_user: swozo

- name: Install docker
  import_playbook: ../docker/install-docker.yml

- name: Prepare file system
  hosts: all
  become: yes
  tasks:
    - name: Create required directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: '0664'
      with_items:
        - "/home/{{ user }}/quiz-app/params"
        - "/home/{{ user }}/quiz-app/questions"
        - "/home/{{ user }}/quiz-app/answers"

    - name: Copy quizapp params file
      ansible.builtin.copy:
        src: "{{ params_path }}"
        dest: "/home/{{ user }}/quiz-app/params/params.json"
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: '0664'
  vars:
    user: swozo
