openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
- url: http://localhost:5000
  description: Generated server url
paths:
  /courses/{id}:
    get:
      tags:
      - course-controller
      operationId: getCourse
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/CourseDetailsDto'
      security:
      - JWT_AUTH: []
    put:
      tags:
      - course-controller
      operationId: editCourse
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateCourseRequest'
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Course'
      security:
      - JWT_AUTH: []
    delete:
      tags:
      - course-controller
      operationId: deleteCourse
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: OK
      security:
      - JWT_AUTH: []
  /courses:
    get:
      tags:
      - course-controller
      operationId: getUserCourses
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CourseDetailsDto'
      security:
      - JWT_AUTH: []
    post:
      tags:
      - course-controller
      operationId: addCourse
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateCourseRequest'
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/CourseDetailsDto'
      security:
      - JWT_AUTH: []
  /courses/{courseId}/students:
    post:
      tags:
      - course-controller
      operationId: addStudentToCourse
      parameters:
      - name: courseId
        in: path
        required: true
        schema:
          type: integer
          format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Course'
      security:
      - JWT_AUTH: []
    delete:
      tags:
      - course-controller
      operationId: removeStudentFromCourse
      parameters:
      - name: courseId
        in: path
        required: true
        schema:
          type: integer
          format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Course'
      security:
      - JWT_AUTH: []
  /auth/login:
    post:
      tags:
      - auth-controller
      summary: Login user
      operationId: login
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/AuthDetailsDto'
  /users/me:
    get:
      tags:
      - user-controller
      operationId: getUserInfo
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/UserDetailsDto'
      security:
      - JWT_AUTH: []
  /service-modules:
    get:
      tags:
      - service-module-controller
      operationId: getModuleList
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ServiceModuleDetailsDto'
      security:
      - JWT_AUTH: []
  /service-modules/{id}:
    get:
      tags:
      - service-module-controller
      operationId: getServiceModule
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ServiceModuleDetailsDto'
      security:
      - JWT_AUTH: []
  /courses/{id}/activities:
    get:
      tags:
      - course-controller
      operationId: getCourseActivityList
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Activity'
      security:
      - JWT_AUTH: []
components:
  schemas:
    ActivityInstructionDto:
      required:
      - body
      type: object
      properties:
        header:
          type: string
        body:
          type: string
    CreateActivityRequest:
      required:
      - description
      - endTime
      - instructionsFromTeacher
      - name
      - selectedModulesIds
      - startTime
      type: object
      properties:
        name:
          type: string
        description:
          type: string
        startTime:
          type: string
          format: date-time
        endTime:
          type: string
          format: date-time
        instructionsFromTeacher:
          type: array
          items:
            $ref: '#/components/schemas/ActivityInstructionDto'
        selectedModulesIds:
          type: array
          items:
            type: integer
            format: int64
    CreateCourseRequest:
      required:
      - activities
      - description
      - expectedStudentCount
      - name
      - studentEmails
      - subject
      type: object
      properties:
        name:
          type: string
        subject:
          type: string
        description:
          type: string
        expectedStudentCount:
          type: integer
          format: int32
        activities:
          type: array
          items:
            $ref: '#/components/schemas/CreateActivityRequest'
        studentEmails:
          type: array
          items:
            type: string
    Activity:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        description:
          type: string
        startTime:
          type: string
          format: date-time
        endTime:
          type: string
          format: date-time
        instructionsFromTeacher:
          type: array
          items:
            $ref: '#/components/schemas/ActivityInstruction'
        modules:
          type: array
          items:
            $ref: '#/components/schemas/ActivityModule'
        course:
          type: integer
          format: int64
    ActivityInstruction:
      type: object
      properties:
        id:
          type: integer
          format: int64
        header:
          type: string
        body:
          type: string
    ActivityLink:
      type: object
      properties:
        id:
          type: integer
          format: int64
        url:
          type: string
        connectionInfo:
          type: string
    ActivityModule:
      type: object
      properties:
        id:
          type: integer
          format: int64
        module:
          $ref: '#/components/schemas/ServiceModule'
        activity:
          $ref: '#/components/schemas/Activity'
        instruction:
          type: string
        links:
          type: array
          items:
            $ref: '#/components/schemas/ActivityLink'
    Course:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        subject:
          type: string
        description:
          type: string
        creationTime:
          type: string
          format: date-time
        activities:
          type: array
          items:
            $ref: '#/components/schemas/Activity'
        students:
          type: array
          items:
            $ref: '#/components/schemas/User'
        teacher:
          $ref: '#/components/schemas/User'
    Role:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
    ServiceModule:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        instructionsFromTechnicalTeacher:
          type: string
        creatorName:
          type: string
        subject:
          type: string
        scheduleType:
          type: string
          enum:
          - JUPYTER
          - DOCKER
        creationTime:
          type: string
          format: date-time
    User:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        surname:
          type: string
        email:
          type: string
        roles:
          type: array
          items:
            $ref: '#/components/schemas/Role'
    ActivityDetailsDto:
      required:
      - activityModules
      - description
      - endTime
      - id
      - instructionsFromTeacher
      - name
      - startTime
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        description:
          type: string
        startTime:
          type: string
          format: date-time
        endTime:
          type: string
          format: date-time
        instructionsFromTeacher:
          type: array
          items:
            $ref: '#/components/schemas/ActivityInstructionDto'
        activityModules:
          type: array
          items:
            $ref: '#/components/schemas/ActivityModuleDetailsDto'
    ActivityModuleDetailsDto:
      required:
      - connectionDetails
      - id
      - instruction
      - module
      type: object
      properties:
        id:
          type: integer
          format: int64
        module:
          $ref: '#/components/schemas/ServiceModuleDetailsDto'
        instruction:
          type: string
        connectionDetails:
          type: array
          items:
            $ref: '#/components/schemas/ServiceConnectionDetailsDto'
    CourseDetailsDto:
      required:
      - activities
      - description
      - id
      - lastActivityTime
      - name
      - students
      - subject
      - teacher
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        teacher:
          $ref: '#/components/schemas/UserDetailsDto'
        lastActivityTime:
          type: string
          format: date-time
        subject:
          type: string
        description:
          type: string
        students:
          type: array
          items:
            $ref: '#/components/schemas/UserDetailsDto'
        activities:
          type: array
          items:
            $ref: '#/components/schemas/ActivityDetailsDto'
    ServiceConnectionDetailsDto:
      required:
      - connectionInstruction
      - serviceName
      type: object
      properties:
        url:
          type: string
        serviceName:
          type: string
        connectionInstruction:
          type: string
        connectionInfo:
          type: string
    ServiceModuleDetailsDto:
      required:
      - creationTime
      - creatorName
      - id
      - instructionsFromTechnicalTeacher
      - name
      - subject
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        instructionsFromTechnicalTeacher:
          type: string
        creatorName:
          type: string
        subject:
          type: string
        creationTime:
          type: string
          format: date-time
    UserDetailsDto:
      required:
      - email
      - name
      - surname
      type: object
      properties:
        name:
          type: string
        surname:
          type: string
        email:
          type: string
    LoginRequest:
      required:
      - email
      - password
      type: object
      properties:
        email:
          type: string
        password:
          type: string
    AuthDetailsDto:
      required:
      - accessToken
      - expiresIn
      - roles
      type: object
      properties:
        accessToken:
          type: string
        expiresIn:
          type: integer
          format: int64
        roles:
          type: array
          items:
            type: string
            enum:
            - STUDENT
            - TEACHER
            - TECHNICAL_TEACHER
            - ADMIN
  securitySchemes:
    JWT_AUTH:
      type: http
      scheme: bearer
      bearerFormat: JWT
