---

- name: Setup SWOZO user
  import_playbook: ../../administration/setup-user.yml
  vars:
    new_user: swozo

- name: Install docker
  import_playbook: ../docker/install-docker.yml

- name: Copy Jitsi config file
  import_playbook: ../../administration/copy-files.yml
  vars:
    path_from: ../software/sozisel/.jitsi_env
    path_to: /home/swozo/.sozisel
    user: swozo

- name: Copy Sozisel docker-compose file
  import_playbook: ../../administration/copy-files.yml
  vars:
    path_from: ../software/sozisel/docker-compose.yml
    path_to: /home/swozo/.sozisel
    user: swozo

- name: Run Sozisel
  hosts: all
  tasks:
    - name: Run Sozisel
      become: yes
      ansible.builtin.shell:
        cmd: docker compose -f /home/swozo/.sozisel/docker-compose.yml --env-file /home/swozo/.sozisel/.jitsi_env up

#          - name: Run sozisel container
#            community.docker.docker_compose:
#              files:
#                - /home/swozo/.sozisel/docker-compose.yml
#              env_file: /home/swozo/.sozisel/.jitsi_env
