---

- name: Run hello-world container
  hosts: all
  tasks:
    - name: Run hello-world container
      community.docker.docker_container:
        name: hello
        image: crccheck/hello-world
        auto_remove: yes
        ports:
          - "80:8000"
      become: yes
